### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by dpryan79** [Genomicsplc/SEW#2]
Can you tag a release? It seems the dependencies have been updated over time. I'd like to be able to build this package again in Bioconda, but it's currently pinned to an ancient version of stitch, which prevents that.

**Comment by rwdavies** [comment]
Yes can do, I'll do this tonight or tomorrow

**Comment by dpryan79** [comment]
Thanks, can you ping me when you do? I'll get the stuff on the Bioconda end sorted out then :)
